/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import database.*;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeArray;

/**
 *
 * @author Suley
 */
public class KampanyaEkle extends javax.swing.JInternalFrame {

    DefaultTableModel dtm;  
    String[] Header = {"Kampanya Adi","Kampanya Fiyatı","Alınacak Kurslar","Ücretsiz Kurslar","ID"};
    
    public KampanyaEkle() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        dtm = new DefaultTableModel(Header,0);
        tabloGuncelle(dtm);
        jTable1.setModel(dtm);
    }
    
    public void tabloGuncelle(DefaultTableModel dtm){
        Database db = new Database("DilKursu","1234");
        ArrayList<Kampanya> kampanya  = db.tumKampanyalariGetir();
        
        dtm.setRowCount(0);
        
        for(Kampanya tmp : kampanya){
            if(tmp.getKampanya_adi().compareTo("Kampanya Seçilmedi") != 0){
                 Object[] obj = {tmp.getKampanya_adi(),tmp.getFiyat(),tmp.getAlinan_kurs_idler(),tmp.getBedava_verilen_kurs_id(),tmp.getKampanyaId()};
                dtm.addRow(obj);
            }           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new java.awt.TextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtKamAdi = new javax.swing.JTextField();
        txtFiyat = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtAlinacak = new javax.swing.JTextField();
        txtUcretsiz = new javax.swing.JTextField();

        jScrollPane1.setViewportView(textArea1);

        jPanel7.setPreferredSize(new java.awt.Dimension(1080, 688));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 470));

        jButton1.setText("Kampanya Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Kampanya Adı");
        jPanel15.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel18.setText("Fiyat:");
        jPanel15.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));
        jPanel15.add(txtKamAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 11, 110, -1));

        txtFiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiyatActionPerformed(evt);
            }
        });
        jPanel15.add(txtFiyat, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 49, 110, -1));

        jLabel19.setText("Alınacak Kurslar");
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 14, -1, -1));

        jLabel20.setText("Ücretsiz Kurs");
        jPanel15.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 52, -1, -1));

        txtAlinacak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlinacakActionPerformed(evt);
            }
        });
        jPanel15.add(txtAlinacak, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 11, 110, -1));
        jPanel15.add(txtUcretsiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 49, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlinacakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlinacakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlinacakActionPerformed

    private void txtFiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiyatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiyatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Database db = new Database("DilKursu","1234");
        String alinacak = txtAlinacak.getText();
        
        String[] alinArr = alinacak.split(",");
        ArrayList<Integer> arr = new ArrayList<Integer>();
        
        for(String tmp : alinArr){
            arr.add(Integer.parseInt(tmp));
        }
        
        db.kampanya_ekle(arr, Integer.parseInt(txtFiyat.getText()) , txtKamAdi.getText() , Integer.parseInt(txtUcretsiz.getText()));
        tabloGuncelle(dtm);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Database db = new Database("DilKursu","1234");
        int row= jTable1.getSelectedRow();
        
        try{
            java.sql.Connection conn = db.database_baglan();
            Statement st = conn.createStatement();
            st.executeQuery("DELETE FROM kampanya WHERE kampanyaid = "+ Integer.parseInt(jTable1.getValueAt(row, 4).toString()) );
        }
        catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
        tabloGuncelle(dtm);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextField txtAlinacak;
    private javax.swing.JTextField txtFiyat;
    private javax.swing.JTextField txtKamAdi;
    private javax.swing.JTextField txtUcretsiz;
    // End of variables declaration//GEN-END:variables
}
