/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import database.*;
import java.util.ArrayList;
import javafx.scene.control.ComboBox;
import javax.swing.JComboBox;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suley
 */
public class KayitEkle extends javax.swing.JInternalFrame {

    boolean kampanyaFlag = false;
    boolean kursFlag = false;
    Kampanya kmp;
    Kurs kurs;
    Ogrenci ogr;
    int row,col;
    String[] header = new String[]{"Kampanya Adı","Fiyat","Alınan Kurslar","Ücretsiz Kurslar"};
    String[] kursHeader = {"İngilizce","Almanca"};
    DefaultTableModel dtm ;
    
    public void kursSecimUnVisible(){
        KursSecimPane.setVisible(false);
        jTable2.setVisible(false);
        jButton6.setVisible(false);
        jScrollPane3.setVisible(false);
    }
    
    public void kursSecimVisible(){
        KursSecimPane.setVisible(true);
        jTable2.setVisible(true);
        jButton6.setVisible(true);
        jScrollPane3.setVisible(true);
    }
    
    public void kampanyaSecimVisible(){
        kampSecim.setVisible(true);
        jTable1.setVisible(true);
        jButton4.setVisible(true);
        jScrollPane1.setVisible(true);
    }
    
    public void kampanyaSecimUnVisible(){
        kampSecim.setVisible(false);
        jTable1.setVisible(false);
        jButton4.setVisible(false);
        jScrollPane1.setVisible(false);
    }
    
    public KayitEkle() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        dtm = new DefaultTableModel(header,0);
        kmp = new Kampanya();

        kursPane.setVisible(false);
        kampanyaSecimUnVisible();
        kursSecimUnVisible();
        
        kursSecim.removeAllItems();
        kursSecim.addItem("İngilizce");
        kursSecim.addItem("Almanca");
        jOptionPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        kampSecim = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        kursPane = new javax.swing.JPanel();
        kursSecim = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        KursSecimPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 688));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("İsim");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Soy İsim");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kimlik Numarası");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Kampanya Seç");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 170, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 170, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefon Numarası");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButton2.setText("Kampanyalar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Ekle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 70, -1));

        kampSecim.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        kampSecim.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        jButton4.setText("Seç");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kampSecim.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 339, 70, 21));

        jPanel1.add(kampSecim, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 620, 360));

        kursPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kursSecim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kursSecim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursSecimActionPerformed(evt);
            }
        });
        kursPane.add(kursSecim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 15, 110, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Listele");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kursPane.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 15, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Kurs Dili");
        kursPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jPanel1.add(kursPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 380, 50));

        KursSecimPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        KursSecimPane.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        jButton6.setText("Ekle");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        KursSecimPane.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 339, 70, 21));

        jPanel1.add(KursSecimPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 620, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 1068, 661));
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Database db = new Database("DilKursu","1234");
        ogr = new Ogrenci(jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText());
        if(jTextField1.getText().compareTo("") != 0 && jTextField2.getText().compareTo("") != 0 && jTextField3.getText().compareTo("") != 0 && jTextField4.getText().compareTo("") != 0 ){
            
            if(kmp.getKampanyaId() == 0 && kampanyaFlag && kursFlag){
                if(!db.ogrenci_ekle(ogr, kurs, kmp.getKampanyaId())){System.out.println("\n"+kampanyaFlag);
                    jOptionPane1.showMessageDialog(null, "Ekleme Yapılamadı");
                }
                else{
                    jOptionPane1.showMessageDialog(null, "Ekleme Yapıldı");
                }
            }
            else if(kampanyaFlag){
                if(!db.ogrenci_ekle(ogr, db.kurs_getir(Integer.parseInt(kmp.getBedava_verilen_kurs_id())), kmp.getKampanyaId())){
                    jOptionPane1.showMessageDialog(null, "Ekleme Yapılamadı");
                }
                else{
                    jOptionPane1.showMessageDialog(null, "Ekleme Yapıldı");
                }
            }else{
                jOptionPane1.showMessageDialog(null, "Ekleme Yapılamadı");
            }
        }
        else{
            jOptionPane1.showMessageDialog(null, "Ekleme Yapılamadı");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String[] header = new String[]{"Kampanya Adı","Fiyat","Alınan Kurslar","Ücretsiz Kurslar","ID"};
        DefaultTableModel dtm = new DefaultTableModel(header,0);
        jTable1.setModel(dtm);
        kampanyaSecimVisible();
        Database db = new Database("DilKursu","1234");
        ArrayList<Kampanya> arr = db.tumKampanyalariGetir();
        
        for(Kampanya tmp: arr){
            Object[] objs = {tmp.getKampanya_adi(),tmp.getFiyat(),tmp.getAlinan_kurs_idler(),tmp.getBedava_verilen_kurs_id(),tmp.getKampanyaId()};
            dtm.addRow(objs);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        row = jTable1.getSelectedRow();
        col = jTable1.getSelectedColumn();
        Database db = new Database("DilKursu", "1234");
        kmp = db.kampanyaGetir(Integer. parseInt(jTable1.getValueAt(row, 4).toString()));
        System.out.println(Integer. parseInt(jTable1.getValueAt(row, 4).toString()));
        kampanyaSecimUnVisible();
        if(Integer. parseInt(jTable1.getValueAt(row, 4).toString()) == 0){
            kursPane.setVisible(true);
        }
        else{
            kursPane.setVisible(false);
        }
        jButton2.setText(jTable1.getValueAt(row, 0).toString());
        kampanyaFlag = true;
    }//GEN-LAST:event_jButton4MouseClicked

    private void kursSecimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursSecimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kursSecimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String[] header = new String[]{"Kurs Adı","Kur Bilgisi","Öğrenci Sayısı","Sınıf","Şube","ID"};
        DefaultTableModel dtm1 = new DefaultTableModel(header,0);
        jTable2.setModel(dtm1);
        kursSecimVisible();
        ArrayList<Kurs> arr = new ArrayList<Kurs>();
        Database db = new Database("DilKursu","1234");
        if( "İngilizce".compareTo((String) kursSecim.getSelectedItem()) == 0){
            arr = db.ingKurslariGetir();
        }
        else if("Almanca".compareTo((String) kursSecim.getSelectedItem()) == 0){
            arr = db.almKurslariGetir();
        }
        
        for(Kurs tmp: arr){
            Object[] objs = {tmp.getKursAdi(),tmp.getKur(),tmp.getOgrenci_sayisi(),tmp.getSinif(),tmp.getSube(),tmp.getKursId()};
            dtm1.addRow(objs);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        row = jTable2.getSelectedRow();
        col = jTable2.getSelectedColumn();
        Database db = new Database("DilKursu", "1234");
        kurs = db.kurs_getir(Integer.parseInt(jTable2.getValueAt(row, 5).toString()) );
        System.out.println(kurs.getKur()+kurs.getKursAdi()+kurs.getKursDili()+kurs.getOgretmenId()+"asfa"+kurs.getKursId());
        kursSecimUnVisible();
        if(kurs != null){
            jOptionPane1.showMessageDialog(null,kurs.getKursDili()+" "+kurs.getKur()+" "+kurs.getSube());
            kursFlag = true;
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        
    }//GEN-LAST:event_jButton6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KursSecimPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel kampSecim;
    private javax.swing.JPanel kursPane;
    private javax.swing.JComboBox<String> kursSecim;
    // End of variables declaration//GEN-END:variables
}
